# Generated by Django 2.1.4 on 2019-01-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projectsapp', '0001_initial'), ('projectsapp', '0002_auto_20190108_1518'), ('projectsapp', '0003_auto_20190108_1558'), ('projectsapp', '0004_auto_20190112_0741'), ('projectsapp', '0005_auto_20190126_0045'), ('projectsapp', '0006_auto_20190126_0110'), ('projectsapp', '0007_auto_20190126_0122'), ('projectsapp', '0008_auto_20190126_0126')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('github_link', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tech_type', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='techonologies',
            field=models.ManyToManyField(blank=True, to='projectsapp.Technology'),
        ),
    ]
