# Generated by Django 2.1.4 on 2019-01-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_auto_20190108_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_school_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='picture_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
