# Generated by Django 2.1.5 on 2019-01-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_auto_20190112_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='picture_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_school_project',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
