# Generated by Django 2.1.5 on 2019-01-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0008_auto_20190126_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='techonologies',
            new_name='technologies',
        ),
    ]
