# Generated by Django 2.1.5 on 2019-01-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0005_auto_20190126_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tech_type', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='techonologies',
            field=models.ManyToManyField(to='resumeapp.Technology'),
        ),
    ]
