# Generated by Django 2.1.5 on 2019-01-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_auto_20190126_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='techonologies',
            field=models.ManyToManyField(blank=True, to='resumeapp.Technology'),
        ),
    ]
