# Generated by Django 2.1.5 on 2019-02-20 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0010_technicalknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalknowledge',
            name='strength',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
